#ifndef UI_CONSTANTS_H
#define UI_CONSTANTS_H

#define MAX_ITEMS 100
#define MAX_SEARCH 256

#define BOX_ONE_WIDTH 80
#define BOX_TWO_WIDTH 29
#define BOX_TWO_HEIGHT 20
#define BOX_THREE_WIDTH 49
#define BOX_ONE_OFFSET_X 1
#define BOX_TWO_OFFSET_X 1
#define BOX_THREE_OFFSET_X (BOX_TWO_OFFSET + BOX_TWO_WIDTH + 1)
#define BOX_ONE_OFFSET_Y 1
#define BOX_TWO_OFFSET_Y 4
#define BOX_THREE_OFFSET_Y 4

#define LEFT_TOP_CORNER 0x256D
#define RIGHT_TOP_CORNER 0x256E
#define LEFT_BOTTOM_CORNER 0x2570
#define RIGHT_BOTTOM_CORNER 0x256F

#define VERTICAL_LINE 0x2500
#define HORIZONTAL_LINE 0x2502

#define DOWN_HORIZONTAL 0x252C
#define VERTICAL_RIGHT 0x251C
#define VERTICAL_LEFT 0x2524
#define UP_HORIZONTAL 0x2534

#define CROSS 0x253C

#endif
